"""Configuration constants for MQuAKE data augmentation."""

import os

# API configuration
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
MODEL_NAME = "gpt-4o"

# Relation ID -> human-readable name
RELATION_NAMES = {
    "P6": "head of government",
    "P19": "place of birth",
    "P20": "place of death",
    "P26": "spouse",
    "P27": "country of citizenship",
    "P30": "continent",
    "P35": "head of state",
    "P36": "capital",
    "P37": "official language",
    "P40": "child",
    "P50": "author",
    "P69": "educated at",
    "P106": "occupation",
    "P108": "employer",
    "P112": "founded by",
    "P136": "genre",
    "P140": "religion",
    "P159": "headquarters location",
    "P169": "CEO",
    "P170": "creator",
    "P175": "performer",
    "P176": "manufacturer",
    "P178": "developer",
    "P286": "head coach",
    "P364": "original language",
    "P407": "language of work",
    "P413": "position played",
    "P449": "original broadcaster",
    "P488": "chairperson",
    "P495": "country of origin",
    "P641": "sport",
    "P740": "location of formation",
    "P800": "notable work",
    "P937": "work location",
    "P1037": "director",
    "P1308": "officeholder",
    "P1412": "languages spoken",
}

# Question templates (relation_id -> template with [X] placeholder)
QUESTION_TEMPLATES = {
    "P6": "What is the name of the current head of the [X] government?",
    "P19": "Which city was [X] born in?",
    "P20": "Which city did [X] die in?",
    "P26": "Who is [X] married to?",
    "P27": "What is the country of citizenship of [X]?",
    "P30": "Which continent is [X] located in?",
    "P35": "What is the name of the current head of state in [X]?",
    "P36": "What is the capital of [X]?",
    "P37": "What is the official language of [X]?",
    "P40": "Who is [X]'s child?",
    "P50": "Who is the author of [X]?",
    "P69": "Which university was [X] educated at?",
    "P106": "What kind of work does [X] do?",
    "P108": "Who is the employer of [X]?",
    "P112": "Who founded [X]?",
    "P136": "What type of music does [X] play?",
    "P140": "Which religion is [X] affiliated with?",
    "P159": "Which city is the headquarter of [X] located in?",
    "P169": "Who is the chief executive officer of [X]?",
    "P170": "Who was [X] created by?",
    "P175": "Who performed [X]?",
    "P176": "Which company is [X] produced by?",
    "P178": "Who is the developer of [X]?",
    "P286": "Who is the head coach of [X]?",
    "P364": "What is the original language of [X]?",
    "P407": "Which language was [X] written in?",
    "P413": "What position does [X] play?",
    "P449": "Who is the original broadcaster of [X]?",
    "P488": "Who is the chairperson of [X]?",
    "P495": "Which country was [X] created in?",
    "P641": "Which sport is [X] associated with?",
    "P740": "Where was [X] founded?",
    "P800": "What is [X] famous for?",
    "P937": "Which city did [X] work in?",
    "P1037": "Who is the director of [X]?",
    "P1308": "Who is the [X]?",
    "P1412": "What language does [X] speak?",
}

# Cloze templates
CLOZE_TEMPLATES = {
    "P6": "The name of the current head of the [X] government is",
    "P19": "[X] was born in the city of",
    "P20": "[X] died in the city of",
    "P26": "[X] is married to",
    "P27": "[X] is a citizen of",
    "P30": "[X] is located in the continent of",
    "P35": "The name of the current head of state in [X] is",
    "P36": "The capital of [X] is",
    "P37": "The official language of [X] is",
    "P40": "[X]'s child is",
    "P50": "The author of [X] is",
    "P69": "The univeristy where [X] was educated is",
    "P106": "[X] works in the field of",
    "P108": "[X] is employed by",
    "P112": "[X] was founded by",
    "P136": "The type of music that [X] plays is",
    "P140": "[X] is affiliated with the religion of",
    "P159": "The headquarters of [X] is located in the city of",
    "P169": "The chief executive officer of [X] is",
    "P170": "[X] was created by",
    "P175": "[X] was performed by",
    "P176": "The company that produced [X] is",
    "P178": "[X] was developed by",
    "P286": "The head coach of [X] is",
    "P364": "The original language of [X] is",
    "P407": "[X] was written in the language of",
    "P413": "[X] plays the position of",
    "P449": "The origianl broadcaster of [X] is",
    "P488": "The chairperson of [X] is",
    "P495": "[X] was created in the country of",
    "P641": "[X] is associated with the sport of",
    "P740": "[X] was founded in the city of",
    "P800": "[X] is famous for",
    "P937": "[X] worked in the city of",
    "P1037": "The director of [X] is",
    "P1308": "The [X] is",
    "P1412": "[X] speaks the language of",
}
